AWSTemplateFormatVersion: '2010-09-09'
Description: Runalytics; a Serverless application that displays information from my running (GPS) watch

Resources:
  RunalyticsBucket:
    Type: AWS::S3::Bucket

  RunalyticsTable:
    Type: AWS::Table::Dynamodb
    Description: Holds all the metadata for the runs
    Properties:
      AttributeDefinitions:
      - AttributeDefinition
      KeySchema:
      - KeySchema
      ProvisionedThroughput:
      - ProvisionedThroughput
